# Generated by Django 4.1.5 on 2023-01-14 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='certificate',
            field=models.CharField(blank=True, choices=[('u', 'U'), ('a', 'A'), ('ua', 'UA'), ('r', 'R'), ('pg-13', 'PG-13'), ('other', 'Other')], max_length=10, null=True, verbose_name='Certificado'),
        ),
    ]
